### ISSUE TITLE
Add a full example use case

### ISSUE THREAD

**Issue by s-ol** [FellowTraveler/Open-Transactions-old#129]
Could someone present a full use case from scratch?
Something like two people exchanging different currencys, showing the creation process of nyms, contracts and currencys.

This would make understanding OT much easier.

**Comment by FellowTraveler** [comment]
On 11/18/12 1:12 PM, S0lll0s wrote:

> Could someone present a full use case from scratch?
> Something like two people exchanging different currencys, showing the
> creation process of nyms, contracts and currencys.
> 
> This would make understanding OT much easier.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FellowTraveler/Open-Transactions/issues/129.

Clearly you haven't watched the videos ... ?

Please go to the wiki and watch all the videos.

**Comment by FellowTraveler** [comment]
Closing this issue since test scripts have been added.

See Open-Transactions/scripts/tests

There's a test script written in bash that runs through much of the OT command-line functionality.

There are also test scripts in PHP and Python, just to show that the high-level API works from those languages now.
