### ISSUE TITLE
Node.js API

### ISSUE THREAD

**Issue by nphyx** [FellowTraveler/Open-Transactions-old#30]
Node.js is javascript for the server-side, essentially, with a lot of extremely attractive features, running on Google's V8 js engine. I don't want this to be a huge priority or anything since it could be a while before I use it, but the three things on the top of my list to develop with are node, couchdb, and open transactions, and I've got a little pet project going with the former two. 

I'd love to toy OT as the backend for a payment gateway whenever I get that far on it. The PHP api is great, I already do PHP professionally, so don't feel like this is a must have, but if you'd like to kick around something hip and new I'd love to see a JS-native API as well. I can always write a little php socket server to handle things too.

**Comment by FellowTraveler** [comment]
OT has an API on the client side (so people can write client-side wallet software for the various different platforms -- obviously I can't write them all.)

However, there is no API on the server side, nor is one currently needed. The server just runs on a certain port, and replies to messages from the clients.

Since Node.JS runs on the server side, I don't see how it would be used with OT...?

If you want to write a custom app that drives the server, you would still write it as a client-app, but then you would run it on the server side and have it take care of all server comms. (For example, if you look at the "cash only" diagram, you'll see a cash-only interface running as an OT client on the server side.)

In the case of using the API on the client side, do you need a special interface for Javascript beyond the existing Java JNI interface?  I'm using SWIG to provide the API in all the various languages, so I would hope SWIG either supports Javascript, or that such support is unnecessary (if Java JNI is accessible in Javascript.)

**Comment by nphyx** [comment]
The Node.js API would operate in the same context as the PHP/Perl/Python, etc. APIs operate (client in context of OT, server in context of a web application). SWIG doesn't support any javascript interpreters, so you wouldn't be able to auto-generate an API for node. Node does however natively implement HTTP, so I may be able to work just with the OT messaging protocol and write up my own interface around it, which would be a lot of fun. If I understand correctly I should be able to communicate directly with the test server using http/ssl? 

There is an xmlrpc lib for node, but a JSON transport protocol would be a great addition in pursuit of that idea. You should be able to serialize any C++ object to JSON trivially, there are libs available, and it's much more bandwidth efficient than XML. I wouldn't object to using xmlrpc though. I skimmed through some of your docs on the messaging protocol, how close are they to complete? Enough that I could begin writing a wrapper?

**Comment by FellowTraveler** [comment]
> The Node.js API would operate in the same context as the PHP/Perl/Python, etc. APIs operate (client in context of OT, server in context of a web application). 

==> OK, makes sense.

> SWIG doesn't support any javascript interpreters, so you wouldn't be able to auto-generate an API for node. 

==> I made a C API for OT, and then all the other APIs are SWIG-generated wrappers of that C API. Therefore, even without SWIG, there are still ways to create a Node.JS wrapper around that same C API.

The relevant files are testwallet/OTAPI_funcdef.h and testwallet/OTAPI.cpp (the functions are written in C++, but they are exported as straight C functions.)

A Node.JS wrapper could be added around those files, using this method:
https://www.cloudkick.com/blog/2010/aug/23/writing-nodejs-native-extensions/

I will probably get around to it at some point, but I don't have time right now or at least for the next few weeks/months.  If you want to do it yourself (looks easy) send me a copy so I can add it to the rest of the project.

> Node does however natively implement HTTP, so I may be able to work just with the OT messaging protocol and write up my own interface around it, which would be a lot of fun. If I understand correctly I should be able to communicate directly with the test server using http/ssl?

==> This wouldn't work.

YES, you can directly communicate with the server over XmlRpc, but then you would need to send an OT Message over that XmlRpc. How will you construct the OTMessage without calling the OTAPI?  Furthermore, the server will send a reply, which is also an OT Message... how will you process the reply?  In fact, generating those messages and processing the replies is the whole job that OT is doing for you in the first place, so you are basically talking about writing an entire replacement version of OT.  It would be much, much easier just to write the Node.JS wrapper (though if you feel up to the task of writing another version of OT, that would be really cool.)

> There is an xmlrpc lib for node, but a JSON transport protocol would be a great addition in pursuit of that idea. You should be able to serialize any C++ object to JSON trivially, there are libs available, and it's much more bandwidth efficient than XML. I wouldn't object to using xmlrpc though. I skimmed through some of your docs on the messaging protocol, how close are they to complete? Enough that I could begin writing a wrapper?

==> If you want to build a version of OT that transports the OT Messages over JSON instead of XmlRpc, this would actually be very easy. 

The transport layer in the library is basically written as a callback function. Here it is for xmlrpc:

OpenTransactions.cpp:159:void OT_XmlRpcCallback(OTServerContract & theServerContract, OTEnvelope & theEnvelope)

There is also a transaction/"xmlrpc_server" and testwallet/"xmlrpc_client" (1 file for server, 1 for client) that would need to be copied and altered for JSON versions of each, but that should also be really easy to do. This is another thing that I'll probably do someday but not anytime soon.

**Comment by nphyx** [comment]
Thanks for all the feedback. I don't know how long it will be before I get into this area of the project (as a pet project, it could be a while between other hobbies). If I get to this before you do I'll definitely shoot you the source so you can publish it. I did look at node extensions after my last note and I think that's the path I'll take. I'm not strong on C++ but  I know it well enough I could probably handle that (my biggest obstacle is that I'm not very handy with a compiler, since 99% of the code I write is in interpreted languages). 

I'll take a look at the transport layer callback too, intuition tells me it should be trivial to create a JSON version based on the XML version but I may be underestimating the complexity of the job.

Thanks again. :)
