### ISSUE TITLE
using Cash functions

### ISSUE THREAD

**Issue by BlueMeanie** [FellowTraveler/Open-Transactions-old#34]
Im also somewhat unclear on how the cash functions work... can you show me an example?

**Comment by FellowTraveler** [comment]
when you run the server, then run the testwallet, try typing "stat" and you will see the various accounts in the wallet.

Next try "get" and when it asks, paste the account number of one of your accounts (in order to download the latest version of it.)

Notice the test wallet, upon receiving the account, also grabs the inbox and the outbox. (Since it needs the latest copy of all three in order to successful negotiate any balance agreement.)  If you are using the API, you have to do this yourself.

Now that you have the latest copy of the account, type "w" which is the withdraw command on the test client. It will ask you for the account ID and for the amount.

The server reply to that command will contain the actual cash, and you will see the Lucre token IDs flash on the screen during the withdrawal process.

Unlike vouchers, you don't have to parse the server reply to read the cash (although you could.)  OT automatically saves the cash to the purse folder (based on server ID and asset type ID). You can directly go and check the file after the withdrawal and see that the new cash tokens have been added there.

I hope you find this useful.

**Comment by BlueMeanie** [comment]
thanks... Im still not altogether clear on how cash transfers work.  Is there any good material on this?  what stops me from just copying the tokens and distributing them?

**Comment by FellowTraveler** [comment]
Alice withdraws a piece of cash. She gives it to Bob (in an email or on a disc or whatever. She could also use sendMessage to send it to Bob through the OT server.) 

Bob deposits the cash.  (Type 'p' to deposit an entire purse, and type 'd' to deposit a single cash note.)

If Bob tries to deposit the same cash twice, the server will see that it is already in the spent-token database, and refuse to redeem it the second time.

Each time you exchange a piece of cash (deposit it and withdraw again, basically) the server will give you a fresh piece that has never been used. This means there is a new untraceable ID every time.

Read the FAQ for OT as well as the Lucre docs for more info.

**Comment by BlueMeanie** [comment]
I see...

so it is up to the owner of the cash to maintain secrecy?  in other words if Eric were to get a copy of the cash tokens before Bob deposits it, they Eric deposit it with no trace of where he obtained it?

**Comment by FellowTraveler** [comment]
Yes, it is up to the owner of the cash to maintain secrecy.

However, keep in mind that when you withdraw some cash tokens, the actual Lucre ID portion of the cash IS ENCRYPTED TO YOUR KEY.  So even if someone stole your files, they would not be able to use your cash without your passphrase.

When you deposit cash, the Lucre IDs are re-encrypted to the server key before being sent to the server.  If you want to export cash from your wallet (and give it to Bob) then the export function will have to decrypt the Lucre ID and re-encrypt it to Bob's public key (Bob's Nym.)  This export function is not written yet, but it is very easy, and I will add it for you as soon as you need it.

For the ultimate double-spending protection, we'll want to add the Chaum algorithm, which makes it possible to expose the account of the double-spender. (Single spenders are not exposed.)  So yes, an algorithm is coming that makes that possible, but some purists prefer NOT to have that option.  Eventually the currency contract will specify the algorithm to be used.  (Currently only Wanger is supported.)

**Comment by BlueMeanie** [comment]
" So even if someone stole your files, they would not be able to use your cash without your passphrase."

ok you lost me again... so if Alice took those files, gave them to Bob, he wouldn't be able to deposit them?  sounds like it does what a check or voucher does.

**Comment by FellowTraveler** [comment]
1) You withdraw 10 clams from the server.  
2) The server sends you a 10-clam note (with the Lucre ID encrypted to your Nym.)
3) If someone steals the note, they cannot use it (because the ID is encrypted.)
4) If you want to pay Bob, you drag the cash to Bob's name.
5) Your wallet then decrypts the Lucre ID of the cash, and re-encrypts it to BOB's public key.
6) When Bob receives the cash, the Lucre ID is already encrypted to his public key and safe for storage on his side.

**Comment by FellowTraveler** [comment]
The difference is that a cheques and vouchers aren't untraceable. Cash is.

Soon there will be an API function for exchanging cash notes (so you don't even need an account to use them.)

**Comment by BlueMeanie** [comment]
ok that was helpful...

do these 6 steps require connecting to a 3rd party server or will my wallet do these operations and then I sent the tokens directly to Bob?

edit:  rather does steps 4-6 require connecting to a server?

**Comment by FellowTraveler** [comment]
The withdrawal process is what CREATES the tokens (before that, the funds were just part of your account balance.)

The server sends you the tokens in the withdrawal reply.  You can give them to Bob and then he can deposit them back in the server.

Therefore, the actual withdrawal is online, with the server, and the actual deposit is online.  You can give him the cash offline but he can't verify it without depositing it (or exchanging it) with the server.

**Comment by BlueMeanie** [comment]
I see, so for so long as you exchange the tokens without the server, there is the possibility for fraud or some other kind of corruption.  

If secrecy is maintained by all parties, tokens can be transferred offline.  The recipients are not guaranteed that the cash the receive is valid until they contact the server.

**Comment by FellowTraveler** [comment]
I see, so for so long as you exchange the tokens without the server, there is the possibility for fraud or some other kind of corruption.

===> Yes, this is why untraceable transactions are online, not offline. (The next step is to add the Chaum algorithm, which reveals the identity of the double-spender. There is still risk using that offline, but more incentive against doing so.)

If secrecy is maintained by all parties, tokens can be transferred offline. The recipients are not guaranteed that the cash the receive is valid until they contact the server

===> This is correct. Even with Chaum's algorithm this is correct.  Because only the spent-token database can reveal whether a token has already been spent. (This is why mints and tokens have revolving expiration dates.)
