### ISSUE TITLE
Components (Certificates & keys) of contracts

### ISSUE THREAD

**Issue by knotwork** [FellowTraveler/Open-Transactions-old#60]
There does not seem to be instructions about the mysterious "certificate" and "certification" and "public key" parts of contracts.

Presumably without putting the correct values for my server into those fields I cannot install a server other then your default server, the example server. There does not seem to be any example nor script nor instructions for creating your own values to plug into those parts of a contract. It seems I might conceivably be able to use gpg to make a public key, but how does that relate to the certificate and the certification? gpg does not seem to mention any way of outputting such things.

**Comment by FellowTraveler** [comment]
> There does not seem to be instructions about the mysterious "certificate" and "certification" and "public key" parts of contracts.

===> Hi.  Currently OT ignores all the keys in a contract, except the "contract" key. That is where you should put the public key for your server.

===> See the ot-sample-contracts folder, you can see there are signed AND unsigned versions of all the contracts, including the demo server contract.

===> To make your own server: Take the unsigned server contract, change the "contract" key inside to whatever public key you want, change the IP / port information to whatever you want, and then sign the contract using the corresponding private key. (You can sign it using the signcontract.exe utility in the client data_folder, or using the ot command line utility.)

===> I think you'll find these helpful:

HOW TO GENERATE THE SSL STUFF, and more importantly, HOW TO SET UP THE TEST DATA TO USE YOUR NEW SSL STUFF:
https://github.com/FellowTraveler/Open-Transactions/blob/master/docs/SSL-NOTES.txt

HOW TO WIPE ALL USER ACCOUNTS but _WITHOUT_ CHANGING THE SERVER'S KEY:
https://github.com/FellowTraveler/Open-Transactions/blob/master/docs/WIPE-USERS-ACCOUNTS.txt

> Presumably without putting the correct values for my server into those fields I cannot install a server other then your default server, the example server. 

===> You are absolutely correct.

> There does not seem to be any example nor script nor instructions for creating your own values to plug into those parts of a contract. 

===> Sorry the docs aren't the best (this project is pretty new). Feel free to add clarifications to the wiki where you feel appropriate.

> It seems I might conceivably be able to use gpg to make a public key, but how does that relate to the certificate and the certification? gpg does not seem to mention any way of outputting such things.

===> Actually, no.  Currently you have to use OpenSSL keys generated by OT.

===> OT is able to import PGP public keys, but it still is not able to import PGP private keys.
===> Therefore it can verify signatures using PGP keys, but it still can't SIGN anything using PGP keys.

===> If you know anyone who has any C/C++ code that will import a PGP private key into OpenSSL format, I'd love a copy of that code, thanks.

-Fellow Traveler

**Comment by knotwork** [comment]
So why do the contracts contain a couple of PGP keys? I do not understand what the certification PGP key is for nor where one is supposed to get it from, and same for the servercertification PGP key. I also do not understand why they are public keys, what use are they? Are they intended to somehow specific which user is promising to honour the contact, identified by a public PGP key instead of a key/cert that only excists withyin open tranasactions? And maybe also identify which server exactly it is that they are making the contract with respect to so it cannot be used by other servers?

If aso, how can anyone know whether the provided public PGP keys actually do correspond to that user and that server? Especially if OT doesn't actually use PGP keyts itself anyway?

Why would I leave your PGP keys in a contract I make? If I replace them, what should I replace them with?

Or are they just useless crud that I should remove entirely?

I do not use PGP, I use GPG. WOuld I put a GPG key inetad of each? If so what GPG keys?

Or do I have to tell GPG to use strict PGP compatibility mode?

What purpose are those tags/sections intended to serve?

**Comment by FellowTraveler** [comment]
> So why do the contracts contain a couple of PGP keys?

===> Those are just test contracts. OT is experimental software.

===> OT _is_ able to import PGP/GPG style public keys, and I've done some testing using those in the past, as a result of that. The PGP keys you see in there are the original ones, I believe from the demo Ricardian contracts distributed by Systemics years ago. (Their software Ricardo is where I got the idea to use Ricardian contracts.)

===> But as I said before, OT is not able to import the PGP/GPG PRIVATE keys (not yet anyway.) I still need some code that will convert PGP-style private keys into OpenSSL format. You cannot use PGP / GPG keys with OT as a result of this, until this is fixed. Until then, you have to use OT with the keys that it generates itself, (it uses OpenSSL FYI.) 

> I do not understand what the certification PGP key is for nor where one is supposed to get it from, and same for the servercertification PGP key. 

===> As I said before, the "contract" key is the only one that OT actually uses right now. The other two are ignored.

===> By changing a single function call, I can make OpenSSL verify the entire chain, all the way up to the CA, instead of merely verifying the public key only.  But I have no reason to do that right now, since I have only been using these contracts for testing.

> I also do not understand why they are public keys, what use are they? Are they intended to somehow specific which user is promising to honour the contact, identified by a public PGP key instead of a key/cert that only excists withyin open tranasactions? And maybe also identify which server exactly it is that they are making the contract with respect to so it cannot be used by other servers?
> If aso, how can anyone know whether the provided public PGP keys actually do correspond to that user and that server? Especially if OT doesn't actually use PGP keyts itself anyway?

===> The purpose of a Ricardian Contract is to put ANY KEYS THAT YOU WANT.

===> You can put an X.509 Cert in there if you want.  You can put several of them, if you want to.

===> You can put an IP address, a Tor address, a Freenet address, -- whatever addresses you want.

===> You can put whatever LEGAL TERMS you want into the contract.

===> These are all things that you have to decide for yourself, if you want to issue a contract. 

---

===> Right now the only key that OT cares about is the "contract" key.

===> The "contract" key is the key that OT will use to verify the signature on the contract.

===> When OT connects to the server, using the IP address in the contract, it will also encrypt all messages to the "contract" key.

===> This means that only the signer of the contract, who chose his own IP address and who chose his key, can receive or open any messages that your OT client sends to that server.  Any change in the contract would also change the server ID (since the ID is a hash of the contract). 

===> I recommend you read these articles:
http://iang.org/papers/ricardian_contract.html
http://www.systemics.com/docs/ricardo/issuer/contract.html
https://github.com/FellowTraveler/Open-Transactions/wiki/Sample-Currency-Contract

> Why would I leave your PGP keys in a contract I make? If I replace them, what should I replace them with? Or are they just useless crud that I should remove entirely?

===> The "contract" key is the only one OT cares about right now. That is the key it will use to verify the signature on the contract. It will also encrypt messages to the server using that key. You can use any public key there (or cert, too, I believe) as long as it was generated by OT.

===> The other keys are just left over from testing, and they also show how a contract might look, if it chooses to use more keys / certs.  But you do not need them for right now -- you can erase them out of the contract.

===> In the near future, there will probably be at least two keys instead of one (one for signing and the other for encryption.)

> I do not use PGP, I use GPG. WOuld I put a GPG key inetad of each? If so what GPG keys? Or do I have to tell GPG to use strict PGP compatibility mode? What purpose are those tags/sections intended to serve?

===> OT is able to import PGP-style keys, and use them to verify signatures, but OT is NOT (yet) able to import PGP private keys. Until I get some import code, OT only operates using keys that it generates itself, using OpenSSL library.

===> If you are looking for a transaction processor based on GPG, I suggest you google for PKTP, which is a cool project.

===> The purpose of the tags / sections depends on how you are using the contract.  If you are running a server, then the server contract contains the server's public key, the server's legal information, the server's IP address, etc.  But if you are issuing a currency, then the currency contract contains information about the currency, legal terms about the currency, the currency symbol, contact information for the issuer, etc etc.

===> Every contract is used for a different purpose, and so contains different information.

===> The ID of any contract is usually the hash of the contract. (You cannot change a contract without also changing its ID). This is like a GPG fingerprint.

===> The contract is signed, and the signature can be verified using the "contract" key located inside the contract.

===> All communications to the IP (or i2p, etc) address inside the contract are encrypted to the public key located inside the contract. This insures that only the signer, who presumably controls the i2p address and the key listed in the contract, can receive or open any messages that you send to him.

-FT

**Comment by FellowTraveler** [comment]
BTW if you are a web developer looking for a GPG-based transaction processor, again, I really recommend you check out PKTP.  It's really good software, and maybe you could put a cool front-end on it. (The GUI is really ugly.)

**Comment by FellowTraveler** [comment]
Also if you are interesting in converting OT to use GPG instead of OpenSSL, check out these classes:

OTToken, OTMint, OTPseudonym, OTAsymmetricKey

The reason I am using OpenSSL right now is because Lucre already uses OpenSSL (Lucre is the code that does the Chaumian blinding for the untraceable cash.)  So I just coded everything else to use the same library.

Thus, if I ever do convert OT over to another crypto lib, such as GPG or Crypto++, it will be necessary for me to either find a replacement for Lucre, or continue linking OpenSSL for that piece.

FYI.

**Comment by knotwork** [comment]
The use of i2p for connect is very interesting, as hosting on hardware that I do not directly physically control pretty much defeats the entire concept of security making all the encryption somewhat moot since an employee of the hosting company could get at the server's keys. I cannot get an incoming port for a server, but i2p gets around that. Do I just use a .i2p top level domain when specifying my server host to accomplish that? What I know of i2p so far makes me unsure that such domain names would automatically work for anyone who had i2p installed and running when they fired up their OT client...

**Comment by FellowTraveler** [comment]
OT currently uses the ZMQ library for all network communications, via a callback function (See testwallet/xmlrpcxx_client.cpp).

If I was going to use OT with i2p, I could (1) add a real i2p address to the contract, such as lksjdflkjsdf.i2p, and (2) I could also add a normal IP address that functions as a proxy, something like this:  127.0.0.1:6969 => lksjdflkjsdf.i2p.

The proxy address would work for the user, as long as the OT install script is smart enough to setup the proxy as described, and as long as i2p is running.  (MEANING OT CODE WOULDN'T HAVE TO CHANGE...)

The ideal solution is to make a NEW CALLBACK to replace the one currently in xmlrpcxx_client.cpp (current version uses ZMQ for transport.)

To do this, I would add a new file, i2p_client.cpp, which would be a copy of xmlrpcxx_client.cpp, except the actual transport callback function would be replaced with an i2p-specific version instead of a ZMQ-specific version, which would handle all the transport DIRECTLY THROUGH I2P, using the I2P API directly.

This would actually be pretty easy to do, since the callback itself is only a few dozen lines long, at most.

**Comment by knotwork** [comment]
I seemed to be getting along fine through the SSL NOTES, until it came to the part about signing the server's contract.

The sign contract utility complains about lack of a wallet file when I tell it to use ~/.ot/server_data, which is presumably needed due to that being where the server-user-ID cert and nym lives.

The server's user-ID nym osn't liked if copied to the client_data, presumably because the client_data uses the client's certificate not the server's certificate? So the signing utility complains about the nym not having the right hash. Since the hash is the nym, changing it would make it a different nym, wouldn't it?

Maybe a "make install" for the ssl directory would save many people many hours of grief, if in fact there is some sequence of file-copying and search-and-replace that can actually make this work...

**Comment by FellowTraveler** [comment]
If you look in the client_data/certs folder, the server's full public / private cert is ALREADY located there as ~/.ot/client_data/certs/pc23gUqPu9Bk1Vl0K5lz3Jp1MYIfjGIBXVWDp1gba9C 

(This is for testing only, since in real life, the server's public info ONLY would be there, not its private too.)

Therefore I suggest you do this for now (copy the server Nym to the client side in order to sign with it.)

---

The Nym's ID is a hash of the Nym's public key.

When OT complains that the ID is wrong, that means it loaded up the key, hashed it, and it didn't match the one it was expecting.

(The IDs it's expecting are listed in notaryServer.xml on the server side, and wallet.xml on the client side.)

> Since the hash is the nym, changing it would make it a different nym, wouldn't it?

For example, let's say the Old Server Cert is the hash (and filename) abc123.

Then let's say you generate a New Server Cert and you copied it over the old one, as filename: ~/.ot/client_data/certs/abc123

When you start OT client, it's already got a list of IDs it's aware of... on the server side, that list is stored in server_data/notaryServer.xml, and on the client side, it's stored in client_data/wallet.xml

Let's say OT tries to sign something using cert abc123. (Remember, we copied the New one OVER the old one, replacing it and using the SAME filename.)

Of course, OT COMPLAINS at this, since hashing the new key produces an entirely different hash: def456

So OT says, "Hey, I loaded up file abc123, but when I hashed the key, I got def456 as the output instead!!! WRONG KEY!!!"

But notice:  You didn't even KNOW the new NymID until now. Until now, you had been copying the new one into the old one's name.  It's only now that you saw the error message, that you know what the new ID actually is (def456).

Therefore, edit the wallet.xml, and change the abc123 to say def456 instead.  THEN RUN AGAIN.  (Error disappears.)

The SSL doc instructions try to explain all this, if you look back at them, it might make more sense now.

---

> Maybe a "make install" for the ssl directory would save many people many hours of grief, if in fact there is some sequence of file-copying and search-and-replace that can actually make this work...

I agree, some kind of script is necessary and is coming soon already.  I think da2ce7's team is already working on it... If you want to email him and ask about it:   da2ce7 at gmail dot com

We are just now reaching the point where someone might use the software with their own cert instead of the test data, and in fact I've just discussed this same script earlier this week with someone else.  If I had more time I would have written it already.  (And if you end up writing one, please send me a copy.)

In any case, it is coming soon, FYI.  In the meantime, the SSL doc instructions will work properly, if you follow them carefully.

Sorry about the hassle,

-FT

**Comment by knotwork** [comment]
I had to edit lines of source code to get it to accept the new nym in the first place. Even though that part seemed to work, the sign contract tool doesn't like that nym. I have to tell it which nym to use, but, it seems to want to be told to use client_data not server_data. All the re-naming of the nym and its cet already took place before the stuff with the uncommented code was used to try to make the actual nym files be signed. But the sign contract tool just doesn't seem to want to use the server_data for the server's user-nym to sign the server contract.

**Comment by FellowTraveler** [comment]
As I said, just copy the server Nym into the client_data side, if you need to use it for signing.  Treat it exactly like it's just another client nym, to get your contract signed.

Sorry again about the hassle. I rarely have to do what you're doing for my own testing, and simply hadn't gotten to the point yet where any other people actually needed to set up a server other than the one that comes with the existing test data.

**Comment by FellowTraveler** [comment]
One more thing:   Recommend you just use the test data for now.

That way, everything will "just work" perfectly.  (And we'll probably have this script for you within the next few weeks, tops.)  Then you can use your own keys all you want, without having to figure out the SSL docs yourself.

**Comment by FellowTraveler** [comment]
> I had to edit lines of source code to get it to accept the new nym in the first place.

FYI, about this:  The Nyms are stored in two files:  the certs folder stores the actual keys / certs, whereas the nyms folder stores the Nymfiles. (The Nymfiles are where a Nym keeps other information such as server registration, transaction #s and request numbers, messages, etc.)

Nymfiles are SIGNED (to prevent tampering.)

WHEN YOU OVERWRITE A CERT, (changing the key) then the SIGNATURE will stop verifying on the Nymfile. (Since it was signed with the old key.)

That is why the SSL directions said to change the OT code:  In order to make OT _ignore_ the bad signature, re-sign it with a good signature, and save it again (so it will work properly thereafter.)

Normally you should never need to do this, since you can generate Nyms from inside OT (using the test GUI or using the API).

Clearly I need to get some kind of script in place for signing server contracts, which would have saved you all this hassle. I simply haven't had the time. But like I said, I think da2ce7 is already working on it.

**Comment by knotwork** [comment]
On the contrary, nothing will work. Even people using the exact same platform I am (Fedora 15, 64 bits) cannot fire up a client to see if they can exchange with other such people via my server.

Everything totally depends on the keys. Any assets created issued exchanged etc are just a waste of space and time, a whole mess of history all of which will have to be reversed, unless there is or will be some routine that will reconcile people's accounts for them once all the real keys get put in place. We cannot even determine whether inserting the hostname into /etc/hosts as an alias for localhost actually works for people on the local net once the rest of the internet is using a world-visible internet address (which for some reason the router will not let people on the local network use, it doesn't route such traffic back onto the local net the way it routes traffic coming from out on the real internet).

No-one is even going to be able to connect to the server to try sending anything to each other until the server's certificate agrees with whatever host they are supposed to be trying to connect to in order to exchange stuff with each other. I can only send people who have fedora 15 64 bit systems a working client to try with but even they won't be able to try unless the server contract directs them to the right host to find the server-to-be-tested at.

Here is what I am doing:

[ot@megabox ot]$ ls ~/.ot/server_data/nyms
lMTANg3U97bwGFJAYKljTXAcy5By6JcLdU4di5AoA4z  puWIXPqHuuR2b0QnmH9TLsGM7u0YQvyUIV3T1WlZvtK  T1Q3wZWgeTUoaUvn9m1lzIK5tn5wITlzxzrGNI8qtaV
[ot@megabox ot]$ ls ~/.ot/client_data/nyms
lMTANg3U97bwGFJAYKljTXAcy5By6JcLdU4di5AoA4z  NOTES.txt  T1Q3wZWgeTUoaUvn9m1lzIK5tn5wITlzxzrGNI8qtaV
[ot@megabox ot]$ cp ~/.ot/server_data/nyms/pu\* ~/.ot/client_data/nyms
[ot@megabox ot]$ ls ~/.ot/client_data/nyms
lMTANg3U97bwGFJAYKljTXAcy5By6JcLdU4di5AoA4z  puWIXPqHuuR2b0QnmH9TLsGM7u0YQvyUIV3T1WlZvtK
NOTES.txt                                    T1Q3wZWgeTUoaUvn9m1lzIK5tn5wITlzxzrGNI8qtaV
[ot@megabox ot]$ ot_signcontract s puWIXPqHuuR2b0QnmH9TLsGM7u0YQvyUIV3T1WlZvtK ~/.ot/client_data ./digitaliscontract.xml
Using 'test' pass phrase for "(null)"

Hashes do NOT match in OTPseudonym::VerifyPseudonym!
puWIXPqHuuR2b0QnmH9TLsGM7u0YQvyUIV3T1WlZvtK
QTuItnvur2WsZqljeh31SLm5GpFHPV57Qa0jBgYIe7i
OT_ASSERT in OTPseudonym.cpp at line 1668
OT_ASSERT in OTPseudonym.cpp at line 1668
Aborted (core dumped)

So evidently the client_data does not agree with the server_data as to what the correct hash for that nym actually is.

the pu\* nym is the server-user's nym.

**Comment by FellowTraveler** [comment]
OT does not ship with any cert named:  puWIXPqHuuR2b0QnmH9TLsGM7u0YQvyUIV3T1WlZvtK 

I assume you are generating it yourself?  Where are you getting the name from?

What happens if you rename the file to QTuItnvur2WsZqljeh31SLm5GpFHPV57Qa0jBgYIe7i and try again?

Can you get me a login to the box?  I can probably figure it out quick.

Can you meet on IRC?  Probably faster that way also.

FYI I'm on #agora and agora.anarplex.net

I'm also on #opentransactions on irc.freenode.net

**Comment by knotwork** [comment]
Maybe when told to sign a server contract instead of an asset contract the signing tool should not look for wallet but instead look for notaryServer, since on the server side it is there rather than in the wallet that it should find the server's nym info?
