### ISSUE TITLE
Chaiscript error on make

### ISSUE THREAD

**Issue by skajake** [FellowTraveler/Open-Transactions-old#68]
/usr/local/include/chaiscript/language/chaiscript_engine.hpp:275: error: ‘void chaiscript::ChaiScript::use(const std::string&)’ is private
xmlrpcxx_client.cpp:1310: error: within this context

**Comment by FellowTraveler** [comment]
Grab the latest version of ChaiScript:

git clone git://github.com/ChaiScript/ChaiScript
cd ChaiScript
mkdir build
cd build
cmake ..
make
sudo make install

This will fix the issue.

**Comment by skajake** [comment]
Thank you for the quick response.  I am looking into doing an iOS GUI for
OT.

On Wed, Feb 15, 2012 at 4:14 PM, FellowTraveler <
reply@reply.github.com

**Comment by FellowTraveler** [comment]
On 2/15/12 2:32 PM, skajake wrote:

> Thank you for the quick response.  I am looking into doing an iOS GUI for
> OT.
> 
> On Wed, Feb 15, 2012 at 4:14 PM, FellowTraveler <
> reply@reply.github.com
> 
> > wrote:
> > 
> > Grab the latest version of ChaiScript:
> > 
> > git clone git://github.com/ChaiScript/ChaiScript
> > cd ChaiScript
> > mkdir build
> > cd build
> > cmake ..
> > make
> > sudo make install
> > 
> > This will fix the issue.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > 
> > https://github.com/FellowTraveler/Open-Transactions/issues/68#issuecomment-3989266
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/FellowTraveler/Open-Transactions/issues/68#issuecomment-3990682

check out the XCode build of OpenSSL 1.0 on github. (I am following the
project.)

It's been a while since OT was built with XCode, and FYI we are about to
release a new build system, so you will probably have to add OT to XCode
yourself to get it running that way instead of g++.

FYI OT might be too bloated as well (for iOS), but lots of bloat can be
removed (see issues list on bloat.)

WOULD IT BE POSSIBLE for you to make a generic project, and TWO SETS OF
VIEWS?  (1 view for iOS and 1 view for MacOS?) That way we can do most
of the testing on MacOS, and can get start ASAP without worrying about
bloat.

(FYI I run MacOS and XCode, but I currently use g++ for building OT.)

FYI also I am about to check in a bunch of fixes (particularly a nasty
crypto bug) and once I do, I will be merging with the new build project
from da2ce7 and dash.

Mail me in private for other news:
fellowtraveler@rayservers.net

P.S. Mac may not ever approve the app so you may be relegated to
jailbroken iOS, though MacOS is all systems go.
